### ISSUE TITLE
SDL: Some keybinds broken due to missing character lookup

### ISSUE THREAD

**Issue by Desour** [luanti-org/luanti#14545]
Opening the chat with `/` is broken on my keyboard setup. I write it with `shift`+`7`. It's instead just interpreted as `7` (= select item in horbar).

**Comment by Montandalar** [comment]
I can see two distinct issues here:
- Certain keys don't register properly, even on the US layout such as `, and the / on the German layout as Desour noted. Those keys can't be bound, or existing custom binds used when bound in earlier, non-SDL versions.
- The default settingtypes values for increasing and decreasing render distance are invalid for SDL2 compared to pre-SDL irrlichtMt. Either non-SDL needs to be dropped and the defaults fixed, or some kind of compatibility layer needs to be there to ensure the binds work no matter SDL is used or not.

**Comment by Montandalar** [comment]
@nephele-gh reported needing to rebind sneak from the default "Shift" to "Left Shift" upon switching from 5.8 to 5.9.0-dev on macOS. Render distance is one thing, but having a core gameplay control like sneak broken by default is not good.

I'll reinforce the point in my last comment. I think a clear upgrade path for existing controls is needed: something like either a layer to translate old/existing bind names to SDL ones or at least working new defaults.

**Comment by grorp** [comment]
Note that SDL2 isn't (yet) enabled by default on macOS. The cause of nephele-gh's bug is probably this, which should be disabled when compiling with SDL:

https://github.com/minetest/minetest/blob/bceef8f5293fb935a78d143976fe1a0eecfdf5de/src/defaultsettings.cpp#L541-L544

**Comment by grorp** [comment]
It seems that SDL fails to provide the information we need here. Like Desour, I have a German keyboard where slash is <kbd>Shift</kbd> + <kbd>7</kbd>.  SDL has a keycode named `SDLK_SLASH`, so I thought we could just listen for that keycode and everything would work.

```diff
diff --git a/irr/src/CIrrDeviceSDL.cpp b/irr/src/CIrrDeviceSDL.cpp
index ecea5bac3..6f08d7fa4 100644
--- a/irr/src/CIrrDeviceSDL.cpp
+++ b/irr/src/CIrrDeviceSDL.cpp
@@ -2,6 +2,7 @@
 // This file is part of the "Irrlicht Engine".
 // For conditions of distribution and use, see copyright notice in irrlicht.h
 
+#include <iostream>
 #ifdef _IRR_COMPILE_WITH_SDL_DEVICE_
 
 #include "CIrrDeviceSDL.h"
@@ -817,6 +818,9 @@ bool CIrrDeviceSDL::run()
                        irrevent.KeyInput.Shift = (SDL_event.key.keysym.mod & KMOD_SHIFT) != 0;
                        irrevent.KeyInput.Control = (SDL_event.key.keysym.mod & KMOD_CTRL) != 0;
                        irrevent.KeyInput.Char = findCharToPassToIrrlicht(mp.SDLKey, key);
+                       std::cerr << "got " << (SDL_event.type == SDL_KEYDOWN ? "SDL_KEYDOWN" : "SDL_KEYUP") << ". " <<
+                                       "SDL_event.key.keysym.sym = " << (int)SDL_event.key.keysym.sym << "; " <<
+                                       "Irrlicht key = " << (int)key << "; assumed char = " << irrevent.KeyInput.Char << std::endl;
                        postEventFromUser(irrevent);
                } break;
 
```

When pressing <kbd>Shift</kbd> + <kbd>7</kbd>, I get the following output:

```
got SDL_KEYDOWN. SDL_event.key.keysym.sym = 1073742049; Irrlicht key = 160; assumed char = 0
got SDL_KEYDOWN. SDL_event.key.keysym.sym = 55; Irrlicht key = 55; assumed char = 55
got SDL_KEYUP. SDL_event.key.keysym.sym = 55; Irrlicht key = 55; assumed char = 55
got SDL_KEYUP. SDL_event.key.keysym.sym = 1073742049; Irrlicht key = 160; assumed char = 0
```

1073742049 = `SDLK_LSHIFT`
55 = `SDLK_7`

`SDLK_SLASH` is not sent.

While searching the SDL issue tracker, I found this: https://github.com/libsdl-org/SDL/issues/3559

**Comment by grorp** [comment]
With the changes to SDL3 coming from https://github.com/libsdl-org/SDL/issues/3559, SDL3 makes it easy to reimplement the behavior of other Irrlicht devices in CIrrDeviceSDL. I have a version that fixes the slash issue here: https://github.com/grorp/minetest/commit/48db7e54497f2a822f457d83252d3805a16fda02 (please note that I didn't do the SDL2 -> SDL3 migration properly) (the numpad +/- keys are still not working properly, haven't investigated)

**Comment by grorp** [comment]
Numpad +/- fixed by #14780.

**Comment by ExeVirus** [comment]
So to clarify: the issues remaining are:

- [ ] MacOS using non-SDL backend
- [ ] shift-F7 not mapping to `/`
- [ ] ` not mapping on US layouts

Anything else?

**Comment by y5nw** [comment]
> ` not mapping on US layouts

Not just the backtick key. Umlaut keys (e.g. `ü`) are not mapped either.

> Anything else?

Dead keys appear to be mapped to the "Left Button" (left mouse button).

**Comment by rubenwardy** [comment]
Related: #14940

**Comment by sfence** [comment]
Looks fine on Mac OS, both in the Minetest build for Intel and ARM.

**Comment by grorp** [comment]
> Looks fine on Mac OS, both in the Minetest build for Intel and ARM.
> 
> I tested two keyboard layouts where "/" required normal key press and shift + key press. Works as expected in both states.

Our macOS builds don't use SDL by default. To reproduce the issue, you have to build with `-DUSE_SDL2=1` explicitly.

**Comment by sfence** [comment]
> > Looks fine on Mac OS, both in the Minetest build for Intel and ARM.
> > I tested two keyboard layouts where "/" required normal key press and shift + key press. Works as expected in both states.
> 
> Our macOS builds don't use SDL by default. To reproduce the issue, you have to build with `-DUSE_SDL2=1` explicitly.

Oh yes. In the Minetest built on Mac with `-DUSE_SDL2=1`, shift + key does not open a chat.

**Comment by SmallJoker** [comment]
To put it blunt: #14964 now causes the same behaviour on the OS-specific device implementations.

**Comment by sfan5** [comment]
Since we're using scancodes now this issue is not valid anymore.
What is `/` on US keyboards becomes `-` on a German keyboard and the key menu shows it correctly.

Allowing bindings with modifier keys is a feature request.

**Comment by y5nw** [comment]
> looks like SDL does not have a scan code for ampersand on the normal keyboard, so there is not workaround.

Unless you have a physical key that maps to the ampersand character in the _unmodified_ state (i.e. without pressing Shift, AltGr, etc), `&` by definition does not have a corresponding scancode.

It is possible to implement keybindings with modifier keys, but this has IMO low priority given that we are not building 3D Vim.

> can this scan code stuff be disabled on Mac builds?

Given that this is a _change_ (not an addition) in how keyboard input is handled, no.
