### ISSUE TITLE
Window scaling under GNOME (Wayland) not working

### ISSUE THREAD

**Issue by realmineplayer** [luanti-org/luanti#15662]
### Luanti version

```true
Luanti 5.10.0 (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.2
Running on Linux/6.12.7 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Fedora Linux 41 (Workstation Edition)

### CPU model

Intel® Core™ i7-8650U × 8

### GPU model

Intel UHD Graphics 620

### Active renderer

OpenGL 4.6

### Summary

When I scale the build-in screen (no matter whether integer or not) and open Luanti on another screen, it scales itself so it looks like it would be "normal" if I open it on build-in with no scaling.

### Steps to reproduce

- Install Luanti with dnf
- scale build-in screen (e.g. 150%)
- open Luanti on another screen

**Comment by sfan5** [comment]
Should be solved with SDL. Please try a development build (5.11.0-dev), if you are able to.

**Comment by sfan5** [comment]
We're still not using SDL for release builds. If you want to check if SDL fixes it you will need to try 5.11-dev or 5.12-dev.

**Comment by realmineplayer** [comment]
just tested it with building the master branch, it still doesn't work

**Comment by grorp** [comment]
Have you tried running Luanti with `SDL_VIDEODRIVER=wayland` set as environment variable?

**Comment by realmineplayer** [comment]
no, will do it later
