### ISSUE TITLE
Segfault / std::bad_alloc in callback on_emerge_area_completion()

### ISSUE THREAD

**Issue by rubenwardy** [luanti-org/luanti#9494]
##### Minetest version
```
5.1.1
```

##### OS / Hardware
Operating system: Ubuntu 18.04
CPU: Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz

##### Summary

Server crashes with the following debug.txt:

```
ERROR[Server]: IRC: Error: Disconnected, reconnecting in one minute.
ERROR[Main]: ServerError: AsyncErr: on_emerge_area_completion: Runtime error from mod 'ctf_flag' in callback on_emerge_area_completion(): std::bad_alloc
ERROR[Main]: stack traceback:
ERROR[Main]:     [C]: in function 'place_schematic'
ERROR[Main]:     ...test/games/capturetheflag/mods/ctf/ctf_map/schem_map.lua:248: in function 'callback'
ERROR[Main]:     ...inetest/games/capturetheflag/mods/ctf/ctf_map/emerge.lua:16: in function 
```

##### Steps to reproduce

Still gathering the information - my server is now running GDB to catch the backtraces. This issue is to remind myself to check my server for data

**Comment by rubenwardy** [comment]
```
from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#6  0x00005555556f588a in ScriptApiEnv::on_emerge_area_completion(irr::core::vector3d<short>, int, ScriptCallbackState*) ()
#7  0x000055555571ff55 in LuaEmergeAreaCallback(irr::core::vector3d<short>, EmergeAction, void*) ()
#8  0x000055555586adec in EmergeThread::run() ()
#9  0x0000555555770a33 in Thread::threadProc(Thread*) ()
#10 0x00007ffff61526df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff6f956db in start_thread (arg=0x7fffedb09700)
    at pthread_create.c:463
#12 0x00007ffff580f88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by rubenwardy** [comment]
```
Thread 7 "Emerge-0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffedb09700 (LWP 18992)]
0x00005555558cadfa in ServerMap::updateVManip(irr::core::vector3d<short>) ()
#0  0x00005555558cadfa in ServerMap::updateVManip(irr::core::vector3d<short>)
    ()
#1  0x000055555595c6f8 in ServerEnvironment::setNode(irr::core::vector3d<short>, MapNode const&) ()
#2  0x000055555571cc04 in ModApiEnvMod::l_set_node(lua_State*) ()
#3  0x00005555556eaf96 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#4  0x00007ffff763ee97 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00007ffff768c27c in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#6  0x00005555556f588a in ScriptApiEnv::on_emerge_area_completion(irr::core::vector3d<short>, int, ScriptCallbackState*) ()
#7  0x000055555571ff55 in LuaEmergeAreaCallback(irr::core::vector3d<short>, EmergeAction, void*) ()
#8  0x000055555586adec in EmergeThread::run() ()
#9  0x0000555555770a33 in Thread::threadProc(Thread*) ()
#10 0x00007ffff61526df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff6f956db in start_thread (arg=0x7fffedb09700)
    at pthread_create.c:463
#12 0x00007ffff580f88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ClobberXD** [comment]
Some relevant chatter from CTF's Discord:

```
ANAND: The modname from which the crash originates is probably just a hoax?
ANAND: Meaning it doesn't come from the mod itself, and instead originates from the C++ code behind the scenes.
ANAND: Bc the latest crash reports furnace, which doesn't even have an on_emerge_area_completion to the best of my knowledge.
...
ANAND: But the issue is triggered by the schematic placement process at the start of a new match
ANAND: And the blame is put on random mods, of course
ANAND: There's only one minetest.emerge_area call in the whole code-base
ANAND: This is wrapped around by a helper function ctf_map.emerge_area_with_callbacks which is called from a couple of places
ANAND: And the suspected area of code, the schem placement code, just before schem placement
ANAND: Maybe MT isn't too happy with emerging a 230x230x140 area?
ANAND: std::bad_alloc is usually associated with the failure to allocate storage
ANAND: So I assume the large emerge area is probably what triggers this crash
ANAND: The question though, is.... why?
ANAND: FYI, furnace makes use of neither minetest.emerge_area nor ctf_map.emerge_area_with_callbacks - it's just completely random
Lone_Wolf: Does this always happen with the same map?
ANAND: I'm not sure
ANAND: I haven't specifically observed it
Lone_Wolf: May help to add a minetest.log() before placing the schem
ANAND: But I suspect this happens with random maps
ANAND: You're right
ANAND: It'll at least help us confirm whether it's the same map that's causing this problem.
ANAND: Btw, here's the line that causes this crash in the engine: https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_map/ctf_map_core/schem_map.lua#L333
```

**Comment by ClobberXD** [comment]
Hmmm...

(from https://github.com/minetest/minetest/issues/9494#issuecomment-609769414)

```
#1  ServerEnvironment::setNode(irr::core::vector3d<short>, MapNode const&) ()
#2  ModApiEnvMod::l_set_node(lua_State*) ()
#3  script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
...
#6  ScriptApiEnv::on_emerge_area_completion(irr::core::vector3d<short>, int, ScriptCallbackState*) ()
```

Looks like the segfault/crash happens due to a race condition when nodes are placed in the emerge area completion callback? CTF places the map's schematic from within this callback, so definitely a lot of node placements. Something else I observed: the Lua stack trace reports the error coming through `minetest.place_schematic`, while GDB's backtrace reports the segfault coming through `minetest.set_node`, which shouldn't be called from within `place_schematic`. Does anyone have an idea as to what's going on? Btw, I haven't been able to reproduce this crash.

**Comment by SmallJoker** [comment]
The bug might have changed or is solved by the emerge thread fixes in May.

**Comment by ClobberXD** [comment]
The server on which this issue continues to manifest (around ten-ish times a day) was updated to the then latest master in the first week of June, IIRC. It'd be nice if @rubenwardy could clarify.

**Comment by rubenwardy** [comment]
The server commit was 9a64a9fd9. I've updated it now

**Comment by Zughy** [comment]
So I guess this have been fixed?

**Comment by rubenwardy** [comment]
No, it still happens constantly. Just never when I'm watching

**Comment by appgurueu** [comment]
what now
